parameters:
#    cabinet_medical.example.class: Cabinet\MedicalBundle\Example

services:
#    cabinet_medical.example:
#        class: %cabinet_medical.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
