<?php

namespace Proxies\__CG__\Cabinet\MedicalBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class cabinet extends \Cabinet\MedicalBundle\Entity\cabinet implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setNom($nom)
    {
        $this->__load();
        return parent::setNom($nom);
    }

    public function getNom()
    {
        $this->__load();
        return parent::getNom();
    }

    public function setAdresse($adresse)
    {
        $this->__load();
        return parent::setAdresse($adresse);
    }

    public function getAdresse()
    {
        $this->__load();
        return parent::getAdresse();
    }

    public function setEmail($email)
    {
        $this->__load();
        return parent::setEmail($email);
    }

    public function getEmail()
    {
        $this->__load();
        return parent::getEmail();
    }

    public function setPhone($phone)
    {
        $this->__load();
        return parent::setPhone($phone);
    }

    public function getPhone()
    {
        $this->__load();
        return parent::getPhone();
    }

    public function setPhonem($phonem)
    {
        $this->__load();
        return parent::setPhonem($phonem);
    }

    public function getPhonem()
    {
        $this->__load();
        return parent::getPhonem();
    }

    public function setFax($fax)
    {
        $this->__load();
        return parent::setFax($fax);
    }

    public function getFax()
    {
        $this->__load();
        return parent::getFax();
    }

    public function addRdvc(\Cabinet\MedicalBundle\Entity\rdv $rdvc)
    {
        $this->__load();
        return parent::addRdvc($rdvc);
    }

    public function removeRdvc(\Cabinet\MedicalBundle\Entity\rdv $rdvc)
    {
        $this->__load();
        return parent::removeRdvc($rdvc);
    }

    public function getRdvc()
    {
        $this->__load();
        return parent::getRdvc();
    }

    public function setUser2(\Cabinet\MedicalBundle\Entity\User $user2 = NULL)
    {
        $this->__load();
        return parent::setUser2($user2);
    }

    public function getUser2()
    {
        $this->__load();
        return parent::getUser2();
    }

    public function setSecurite(\Cabinet\MedicalBundle\Entity\securite $securite = NULL)
    {
        $this->__load();
        return parent::setSecurite($securite);
    }

    public function getSecurite()
    {
        $this->__load();
        return parent::getSecurite();
    }

    public function addMedecin(\Cabinet\MedicalBundle\Entity\medecin $medecin)
    {
        $this->__load();
        return parent::addMedecin($medecin);
    }

    public function removeMedecin(\Cabinet\MedicalBundle\Entity\medecin $medecin)
    {
        $this->__load();
        return parent::removeMedecin($medecin);
    }

    public function getMedecin()
    {
        $this->__load();
        return parent::getMedecin();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function addOpmedcab(\Cabinet\MedicalBundle\Entity\operationmed $opmedcab)
    {
        $this->__load();
        return parent::addOpmedcab($opmedcab);
    }

    public function removeOpmedcab(\Cabinet\MedicalBundle\Entity\operationmed $opmedcab)
    {
        $this->__load();
        return parent::removeOpmedcab($opmedcab);
    }

    public function getOpmedcab()
    {
        $this->__load();
        return parent::getOpmedcab();
    }

    public function setImage($image)
    {
        $this->__load();
        return parent::setImage($image);
    }

    public function getImage()
    {
        $this->__load();
        return parent::getImage();
    }

    public function preUpload()
    {
        $this->__load();
        return parent::preUpload();
    }

    public function upload()
    {
        $this->__load();
        return parent::upload();
    }

    public function storeFilenameForRemove()
    {
        $this->__load();
        return parent::storeFilenameForRemove();
    }

    public function removeUpload()
    {
        $this->__load();
        return parent::removeUpload();
    }

    public function getAbsolutePath()
    {
        $this->__load();
        return parent::getAbsolutePath();
    }

    public function getWebPath()
    {
        $this->__load();
        return parent::getWebPath();
    }

    public function addConsultationcab(\Cabinet\MedicalBundle\Entity\consultation $consultationcab)
    {
        $this->__load();
        return parent::addConsultationcab($consultationcab);
    }

    public function removeConsultationcab(\Cabinet\MedicalBundle\Entity\consultation $consultationcab)
    {
        $this->__load();
        return parent::removeConsultationcab($consultationcab);
    }

    public function getConsultationcab()
    {
        $this->__load();
        return parent::getConsultationcab();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'nom', 'adresse', 'email', 'phone', 'phonem', 'fax', 'image', 'rdvc', 'consultationcab', 'opmedcab', 'user2', 'securite', 'medecin');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}