<?php

namespace Cabinet\MedicalBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * prisechargeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class prisechargeRepository extends EntityRepository
{
}
