<?php

namespace Cabinet\MedicalBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * rdvRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class rdvRepository extends EntityRepository
{
}
