<?php

namespace Cabinet\MedicalBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class prisechargeController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Cabinet\MedicalBundle\Controller\prisechargeController();
        return $instance;
    }
}
