<?php

namespace Proxies\__CG__\Cabinet\MedicalBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class rdv extends \Cabinet\MedicalBundle\Entity\rdv implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setTitre($titre)
    {
        $this->__load();
        return parent::setTitre($titre);
    }

    public function getTitre()
    {
        $this->__load();
        return parent::getTitre();
    }

    public function setDate($date)
    {
        $this->__load();
        return parent::setDate($date);
    }

    public function getDate()
    {
        $this->__load();
        return parent::getDate();
    }

    public function setNum($num)
    {
        $this->__load();
        return parent::setNum($num);
    }

    public function getNum()
    {
        $this->__load();
        return parent::getNum();
    }

    public function setMed(\Cabinet\MedicalBundle\Entity\medecin $med = NULL)
    {
        $this->__load();
        return parent::setMed($med);
    }

    public function getMed()
    {
        $this->__load();
        return parent::getMed();
    }

    public function setPatient(\Cabinet\MedicalBundle\Entity\patient $patient = NULL)
    {
        $this->__load();
        return parent::setPatient($patient);
    }

    public function getPatient()
    {
        $this->__load();
        return parent::getPatient();
    }

    public function setCabinet(\Cabinet\MedicalBundle\Entity\cabinet $cabinet = NULL)
    {
        $this->__load();
        return parent::setCabinet($cabinet);
    }

    public function getCabinet()
    {
        $this->__load();
        return parent::getCabinet();
    }

    public function setActive($active)
    {
        $this->__load();
        return parent::setActive($active);
    }

    public function getActive()
    {
        $this->__load();
        return parent::getActive();
    }

    public function setUser4(\Cabinet\MedicalBundle\Entity\User $user4 = NULL)
    {
        $this->__load();
        return parent::setUser4($user4);
    }

    public function getUser4()
    {
        $this->__load();
        return parent::getUser4();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'titre', 'date', 'num', 'active', 'med', 'user4', 'patient', 'cabinet');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}